### ISSUE TITLE
Incomplete extraction of Bitpool archive

### ISSUE THREAD

**Issue by TheRogueArchivist** [mnadareski/UnshieldSharp#7]
On the game http://redump.org/disc/35476/, UnshieldSharp crashes with: 
```Unhandled exception. System.IO.IOException: The parameter is incorrect. : 'K:\DATA1.cab'
   at System.IO.Strategies.FileStreamHelpers.ThrowInvalidArgument(SafeFileHandle handle)
   at System.IO.Strategies.OSFileStreamStrategy.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.Strategies.BufferedFileStreamStrategy.Seek(Int64 offset, SeekOrigin origin)
   at UnshieldSharp.Cabinet.InstallShieldCabinet.FileName(Int32 index) in B:\Programs\GitHub\UnshieldSharp\UnshieldSharp\Cabinet\InstallShieldCabinet.cs:line 110
   at Test.Program.ProcessCabinetPath(String file, Boolean outputInfo, Boolean extract, String outputDirectory) in B:\Programs\GitHub\UnshieldSharp\Test\Program.cs:line 251
   at Test.Program.Main(String[] args) in B:\Programs\GitHub\UnshieldSharp\Test\Program.cs:line 94
```
This crash occurs before fully extracting the contents of the archive. I verified with another program that there are further extractable contents.

**Comment by TheRogueArchivist** [comment]
Fixed as of latest commit.
