### ISSUE TITLE
`Failed to get file descriptor 0` issue on Final Fantasy XIV discs

### ISSUE THREAD

**Issue by Whovian9369** [mnadareski/UnshieldSharp#9]
```
$ ~/path/to/UnshieldSharp-9dc403ffc18d60c3016fcfbbd5499ee275a46ced_net6.0_linux-x64_1.6.9-55/Test -o data1_hdr data1.hdr
Failed to get file descriptor 0
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Test.Program.ProcessCabinetPath(String file, Boolean outputInfo, Boolean extract, String outputDirectory) in C:\projects\unshieldsharp\Test\Program.cs:line 251
   at Test.Program.Main(String[] args) in C:\projects\unshieldsharp\Test\Program.cs:line 94
[1]    228259 abort       -o data1_hdr data1.hdr
```

Ran `Test -i data1.hdr` to see if it still errored or not, and it did after listing a number of other files first: [UnshieldSharp_Error.log](https://github.com/mnadareski/UnshieldSharp/files/10495821/UnshieldSharp_Error.log)

Small edit:
So I decided to look at the log info again right after posting this issue, and found that it seems to fail at getting the following file descriptors before giving the above error:
```
Failed to get file descriptor 0
Failed to get file descriptor 1
Failed to get file descriptor 7
Failed to get file descriptor 8
Failed to get file descriptor 9
Failed to get file descriptor 10
Failed to get file descriptor 51
Failed to get file descriptor 58
Failed to get file descriptor 59
Failed to get file descriptor 126
````

**Comment by Whovian9369** [comment]
Files appear to extract correctly, with my only complaint being some paths extracted as `output/folder1\folder2/file.ext` instead of expected `/` being used in all parts of path.

Edit: Forgot to attach a log. [unshieldsharp.log](https://github.com/user-attachments/files/17221647/unshieldsharp.log)

Edit: Mentioned issue with path seems to not be simply visual, and actually writes to the filesystem as such. Getting assistance from a friend to see if this is an issue with me using UnshieldSharp via WSL2, or if it's an actual UnshieldSharp issue.

Further Edit: c6a75c3ccaa760ac02b8f1d7b30c62aaecafdc4c seems to completely fix my issues, but I'll keep an eye out for issues that I see.
